// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArknCheckbox: typeof import('./src/UI/ArknCheckbox.vue')['default']
    ArknInput: typeof import('./src/UI/ArknInput.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    Card: typeof import('./src/UI/Card.vue')['default']
    ChooseRange: typeof import('./src/components/ChooseRange.vue')['default']
    Details: typeof import('./src/components/Details.vue')['default']
    GreenShopIcon: typeof import('./src/UI/Icons/GreenShopIcon.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDivider: typeof import('naive-ui')['NDivider']
    NModal: typeof import('naive-ui')['NModal']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    OrundumIcon: typeof import('./src/UI/Icons/OrundumIcon.vue')['default']
    Others: typeof import('./src/components/Others.vue')['default']
    PrimeCard: typeof import('./src/components/PrimeCard.vue')['default']
    Result: typeof import('./src/components/Result.vue')['default']
    Rules: typeof import('./src/components/Rules.vue')['default']
  }

}
